In [25]:
import numpy as np
from numpy.linalg import matrix_rank


In [5]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
# Transpose

In [10]:
A_transpose = A.transpose()
A_transpose

array([[1, 3],
       [2, 4]])

In [11]:
# Dot product and Addition

In [15]:
# Streaching

B = np.array([[5,0],[0,5]])
C = np.array([[1],[1]])
BdotC = np.dot(B,C)
BdotC

array([[5],
       [5]])

In [17]:
# Rotation

D = np.array([[0,-1],[1,0]])
C = np.array([[1],[1]])
DdotC = np.dot(D,C)
DdotC

array([[-1],
       [ 1]])

In [18]:
# Matrices as linear transformation

In [19]:
# Reflection
E = np.array([[0,1],[1,0]])
F = np.array([[1],[0]])
np.dot(E,F)

array([[0],
       [1]])

In [20]:
# Projection
G = np.array([[1,0],[0,0]])
H = np.array([[1],[1]])
np.dot(G,H)

array([[1],
       [0]])

$$\left[ \begin{array}{ccc} a & 0 & 0 \\ 0 & b &0\ \\ 0 & 0  & c \end{array} \right ]Diagonal$$ 
<p></p>

$$\left[ \begin{array}{ccc} a & b & c \\ 0 & d & e\ \\ 0 & 0  & f \end{array} \right ]upper-triangular$$ 


### Rank
- The rank of A is the dimension of the colum space of A
- It also equals the dimentios of the _row space_ of A ( the subspace of vectos which may be written as linear cimpbination of the rows of A)

In [26]:
A = np.array([[1,0],[2,3],[1,3]])
matrix_rank(A)

2

In [27]:
A

array([[1, 0],
       [2, 3],
       [1, 3]])

In [28]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])