## Matrix Programming
### Indexing

In [2]:
import numpy as np

In [3]:
block = np.array([[10,20,30,40],[110,120,130,140],[210,220,230,240]])
block

array([[ 10,  20,  30,  40],
       [110, 120, 130, 140],
       [210, 220, 230, 240]])

In [5]:
# Can slicke arrays like list or strings
block[0:3, 0:2]  # selects the first 3 rows and the fist 2 columns

array([[ 10,  20],
       [110, 120],
       [210, 220]])

In [6]:
# Can assign to slices
block[1, 1:3] = 0  
block

array([[ 10,  20,  30,  40],
       [110,   0,   0, 140],
       [210, 220, 230, 240]])

In [7]:
# slice on both sides to shift data
vector = np.array([10,20,30,40])
vector[0:3] = vector[1:4]
vector

array([20, 30, 40, 40])

In [8]:
# Can use list or arrays as subscripts
vector = np.array([0,10,20,30])
vector

array([ 0, 10, 20, 30])

In [10]:
subscript = [3,1,2] 
vector[subscript]  # give the 3rd, first, second location from vector array

array([30, 10, 20])

In [11]:
## also works in multiple dimentions
square = np.array([[5,6], [7,8]])
square[[1]]

array([[7, 8]])

In [12]:
# Comparison
vector

array([ 0, 10, 20, 30])

In [13]:
vector< 25  # data type is boolean

array([ True,  True,  True, False], dtype=bool)

In [14]:
# Use Boolean subscript as a mask
vector

array([ 0, 10, 20, 30])

In [17]:
vector[vector < 25] # show me  true values instead of boolean

array([ 0, 10, 20])

In [22]:
# Use masking for assignmetn
a = np.array([0,1,2,3])
mask = np.array([True, False, True, False])
a[mask] = np.array([100,101,102,103])

ValueError: NumPy boolean array indexing assignment cannot assign 4 input values to the 2 output values where the mask is true

In [23]:
# putmask function woks slight diffrent
a

array([0, 1, 2, 3])

In [24]:
mask

array([ True, False,  True, False], dtype=bool)

In [27]:
np.putmask(a,mask, np.array([100,101,102,103]))
a

array([100,   1, 102,   3])

In [29]:
# Python dies not allow objects to re-define teh meaning of "and/or/not

vector = np.array([0,10,20,30])
vector <=20

array([ True,  True,  True, False], dtype=bool)

In [30]:
(vector <=20) and (vector>=20)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
# Way around this is to use logical_and/ logical_or fucnitons
np.logical_and(vector<=20, vector>=20)

array([False, False,  True, False], dtype=bool)

In [33]:
# OR | for or , and
(vector<=20) &(vector >=20)

array([False, False,  True, False], dtype=bool)

In [34]:
# USe where instead of if/else
vector

array([ 0, 10, 20, 30])

In [36]:
np.where(vector<25, vector, 0)

array([ 0, 10, 20,  0])

In [39]:
np.where(vector> 25,vector/10, vector)

array([  0.,  10.,  20.,   3.])

## Review
- Arrays can bea sliced
- Or subscripted with vecors of indices
- Or masked with conditionals
- Should not use loops to index