## Matrix programming
### Linear Algebra

In [2]:
import numpy as np

#### Numpy arrays make operations on rectangular data eazy
#### But they are not quite mathematical matrices

In [3]:
a = np.array([[1,2],[3,4]])

In [4]:
a * a

array([[ 1,  4],
       [ 9, 16]])

Operations act _elementwise_

So this dies what you thing

In [5]:
a + a

array([[2, 4],
       [6, 8]])

And Numpy is sensible about _scalar_values

In [6]:
a + 1

array([[2, 3],
       [4, 5]])

#### Lots of useful utilities

In [11]:
a

array([[1, 2],
       [3, 4]])

In [8]:
np.sum(a)  # adds all values of array

10

In [9]:
np.sum(a,0)  # adds columns

array([4, 6])

In [10]:
np.sum(a,1)  # adds rows

array([3, 7])

In [13]:
np.sum(a,2)  # wrong? its a 2-dimentional array

ValueError: 'axis' entry is out of bounds

### Example: disease statistics
- one row per patient
- columns are hourly responsive Tcell counts

In [15]:
np.data[:, 0]  # t0 coutn for all patients

AttributeError: module 'numpy' has no attribute 'data'

In [16]:
# Real matrix multiplication

In [17]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [19]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [23]:
v = np.arange(3)  # [0,1,2]
v

array([0, 1, 2])

In [25]:
np.dot(v,v)  # 0*0 + 1*1 + 2*2

5

### Dot products only work for sensible shapes

In [27]:
np.dot(np.ones((2,3)), np.ones((2,3)))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

### Numpy does not distingush row/col vectors

In [28]:
v = np.array((1,2))
a = np.array([[1,2],[3,4]])
np.dot(v,a)

array([ 7, 10])

In [29]:
np.dot(a,v)

array([ 5, 11])

### Can also use the _matrix_ sublclass of _arrays_

In [30]:
m = np.matrix([[1,2], [3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [31]:
m * m

matrix([[ 7, 10],
        [15, 22]])

 #### Use `np.matrix(a)` or `np.array(m)` to convert

### Which should you use?
If you problem is linear algebra, _matrix_ will probally be more convenient
- Treats vectors asn Nx1 matrices
Otherwise, use array
- Especially if you're representing grids, rather than mathematical matrices